### ISSUE TITLE
Add Account Sequence Diagram

### ISSUE THREAD

**Issue by jonathangetachew** [jonathangetachew/FinCo#10]
<img width="1033" alt="CreateAccount - Sequence Diagram" src="https://user-images.githubusercontent.com/11243076/73685064-0ebeb880-468b-11ea-9b51-fdc0a87de1b3.png">
<img width="1106" alt="Deposit - Sequence Diagram" src="https://user-images.githubusercontent.com/11243076/73685065-0ebeb880-468b-11ea-8a93-7e5be474015b.png">

**Comment by ammaratef45** [comment]
@jonathangetachew let's make the deposit in #11 and make this for the create case only
